version: '3'

services:
    # Serve static webpages and proxy to APIs
    # CRA dev server in dev and nginx in production
    webserver:
        build:
            target: development # Determine dev or prod
        restart: unless-stopped
        volumes:
            - ./client:/home/node/app

    api:
        command: nodemon dist/workers/api.worker.js
        restart: unless-stopped
        volumes:
            - ./server/dist:/home/node/app/dist
    
    leader:
        command: nodemon dist/workers/leader.worker.js
        restart: unless-stopped
        volumes:
            - ./server/dist:/home/node/app/dist

    offer:
        command: nodemon dist/workers/offer.worker.js
        restart: unless-stopped
        volumes:
            - ./server/dist:/home/node/app/dist

    live:
        command: nodemon dist/workers/live.worker.js
        restart: unless-stopped
        volumes:
            - ./server/dist:/home/node/app/dist

    nfl:
        command: nodemon dist/workers/nfl.worker.js
        restart: unless-stopped
        volumes:
            - ./server/dist:/home/node/app/dist

    db: # Postgres with Timescale extension
        ports:
            - 5432:5432 # Expose ports
        restart: unless-stopped
        volumes:
          - dbdata:/data/db

    redis:
        ports:
            - 6379:6379 # Expose ports

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
