version: '3'

services:
    webserver:
        build:
            context: .
            dockerfile: ./client/Dockerfile
            target: ${NODE_ENV}
        container_name: webserver
        restart: unless-stopped
        ports:
            - 80:${INNER_PORT}
            - 443:443
        networks:
            - app-network
        depends_on:
            - api
            - live
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - ./client:/home/node/app
            - /home/node/app/node_modules

    api:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        container_name: api
        env_file: .env
        environment:
            - NODE_ENV=$NODE_ENV
            - DB_USER=$DB_USER
            - DB_PASS=$DB_PASS
            - DB_HOST=db
            - DB_PORT=$DB_PORT
            - DB_NAME=$DB_NAME
            - REDIS_HOST=redis
            - REDIS_PORT=$REDIS_PORT
        networks:
            - app-network
        depends_on:
            - db
            - redis
        command: 
            ./node_modules/.bin/nodemon app.js
        volumes:
            - ./server:/home/node/app
            - /home/node/app/node_modules
    
    leader:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        container_name: leader
        env_file: .env
        environment:
            - NODE_ENV=$NODE_ENV
            - DB_USER=$DB_USER
            - DB_PASS=$DB_PASS
            - DB_HOST=db
            - DB_PORT=$DB_PORT
            - DB_NAME=$DB_NAME
            - REDIS_HOST=redis
            - REDIS_PORT=$REDIS_PORT
        networks:
            - app-network
        depends_on:
            - db
            - redis
        command: 
            ./node_modules/.bin/nodemon workers/leader.worker.js
        volumes:
            - ./server:/home/node/app
            - /home/node/app/node_modules

    offer:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        container_name: offer
        env_file: .env
        environment:
            - NODE_ENV=$NODE_ENV
            - DB_USER=$DB_USER
            - DB_PASS=$DB_PASS
            - DB_HOST=db
            - DB_PORT=$DB_PORT
            - DB_NAME=$DB_NAME
            - REDIS_HOST=redis
            - REDIS_PORT=$REDIS_PORT
        networks:
            - app-network
        depends_on:
            - db
            - redis
        command: 
            ./node_modules/.bin/nodemon workers/offer.worker.js
        volumes:
            - ./server:/home/node/app
            - /home/node/app/node_modules

    live:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        container_name: live
        env_file: .env
        environment:
            - NODE_ENV=$NODE_ENV
            - DB_USER=$DB_USER
            - DB_PASS=$DB_PASS
            - DB_HOST=db
            - DB_PORT=$DB_PORT
            - DB_NAME=$DB_NAME
            - REDIS_HOST=redis
            - REDIS_PORT=$REDIS_PORT
            - PORT=$LIVE_PORT
        networks:
            - app-network
        depends_on:
            - db
            - redis
        command: 
            ./node_modules/.bin/nodemon workers/live.worker.js
        volumes:
            - ./server:/home/node/app
            - /home/node/app/node_modules

    db:
        image: timescale/timescaledb:latest-pg12
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASSWORD=$DB_PASS
            - POSTGRES_DB=$DB_NAME
        volumes:
          - dbdata:/data/db
          - ./server/db/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
        networks:
          - app-network

    redis:
        image: redis
        container_name: redis
        env_file: .env
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
