import service from '../services/getWeekEntries.service';
import { ArrayTest } from '../../util/util.tests';

describe('getWeekEntries service', () => {
  test('Valid request returns data', ArrayTest(
    service, { },
    [{
      Contest: {
        budget: 10000,
        id: 1,
        name: 'Ball Street Big One',
        nflweek: Number(process.env.WEEK),
      },
      ContestId: 1,
      DEF1: null,
      FLEX1: null,
      FLEX2: null,
      K1: null,
      QB1: null,
      RB1: 31885,
      RB2: null,
      TE1: null,
      User: {
        email: 'email1@gmail.com', id: 1, name: 'bot', verified: true,
      },
      UserId: 1,
      WR1: null,
      WR2: null,
      pointtotal: 10000,
    }, {
      Contest: {
        budget: 10000,
        id: 1,
        name: 'Ball Street Big One',
        nflweek: Number(process.env.WEEK),
      },
      ContestId: 1,
      DEF1: null,
      FLEX1: null,
      FLEX2: null,
      K1: null,
      QB1: null,
      RB1: 31885,
      RB2: null,
      TE1: null,
      User: {
        email: 'email2@gmail.com', id: 2, name: 'bot', verified: true,
      },
      UserId: 2,
      WR1: null,
      WR2: null,
      pointtotal: 10000,
    }, {
      Contest: {
        budget: 10000,
        id: 1,
        name: 'Ball Street Big One',
        nflweek: Number(process.env.WEEK),
      },
      ContestId: 1,
      DEF1: null,
      FLEX1: null,
      FLEX2: null,
      K1: null,
      QB1: null,
      RB1: 31885,
      RB2: null,
      TE1: null,
      User: {
        email: 'email3@gmail.com', id: 3, name: 'bot', verified: true,
      },
      UserId: 3,
      WR1: null,
      WR2: null,
      pointtotal: 10000,
    }, {
      Contest: {
        budget: 10000,
        id: 2,
        name: 'Private Contest',
        nflweek: Number(process.env.WEEK),
      },
      ContestId: 2,
      DEF1: 21,
      FLEX1: null,
      FLEX2: null,
      K1: 30266,
      QB1: null,
      RB1: 31885,
      RB2: null,
      TE1: null,
      User: {
        email: 'email1@gmail.com', id: 1, name: 'bot', verified: true,
      },
      UserId: 1,
      WR1: null,
      WR2: null,
      pointtotal: 10000,
    }, {
      Contest: {
        budget: 10000,
        id: 2,
        name: 'Private Contest',
        nflweek: Number(process.env.WEEK),
      },
      ContestId: 2,
      DEF1: null,
      FLEX1: null,
      FLEX2: null,
      K1: 30266,
      QB1: null,
      RB1: 31885,
      RB2: null,
      TE1: null,
      User: {
        email: 'email2@gmail.com', id: 2, name: 'bot', verified: true,
      },
      UserId: 2,
      WR1: 32398,
      WR2: 28026,
      pointtotal: 1500,
    }, {
      Contest: {
        budget: 10000,
        id: 2,
        name: 'Private Contest',
        nflweek: Number(process.env.WEEK),
      },
      ContestId: 2,
      DEF1: null,
      FLEX1: null,
      FLEX2: null,
      K1: 30266,
      QB1: null,
      RB1: 31885,
      RB2: null,
      TE1: null,
      User: {
        email: 'email3@gmail.com', id: 3, name: 'bot', verified: true,
      },
      UserId: 3,
      WR1: null,
      WR2: null,
      pointtotal: 500,
    },
    {
      Contest: {
        budget: 10000,
        id: 3,
        name: 'Public Contest 2',
        nflweek: Number(process.env.WEEK),
      },
      ContestId: 3,
      DEF1: 21,
      FLEX1: null,
      FLEX2: null,
      K1: 30266,
      QB1: null,
      RB1: 31885,
      RB2: null,
      TE1: null,
      User: {
        email: 'email1@gmail.com', id: 1, name: 'bot', verified: true,
      },
      UserId: 1,
      WR1: null,
      WR2: null,
      pointtotal: 10000,
    }, {
      Contest: {
        budget: 10000,
        id: 3,
        name: 'Public Contest 2',
        nflweek: Number(process.env.WEEK),
      },
      ContestId: 3,
      DEF1: null,
      FLEX1: null,
      FLEX2: null,
      K1: 30266,
      QB1: null,
      RB1: 31885,
      RB2: null,
      TE1: null,
      User: {
        email: 'email2@gmail.com', id: 2, name: 'bot', verified: true,
      },
      UserId: 2,
      WR1: 32398,
      WR2: 28026,
      pointtotal: 1500,
    }, {
      Contest: {
        budget: 10000,
        id: 3,
        name: 'Public Contest 2',
        nflweek: Number(process.env.WEEK),
      },
      ContestId: 3,
      DEF1: null,
      FLEX1: null,
      FLEX2: null,
      K1: 30266,
      QB1: null,
      RB1: 31885,
      RB2: null,
      TE1: null,
      User: {
        email: 'email3@gmail.com', id: 3, name: 'bot', verified: true,
      },
      UserId: 3,
      WR1: null,
      WR2: null,
      pointtotal: 500,
    }],
  ));
});
