name: Build and Push - Client

on:
  push:
    branches: [ master ]
    paths:
      - 'client/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-client:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build client image
      run: docker build . -f ./client/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/ball_street:client --target production

    - name: Push client image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ball_street:client
