name: Lint and Test - Server

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'server/**'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  lint-and-test-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create .env file from example
      run: cp example.env .env

    - name: Create secret file from example
      run: cp secret.example.ts secret.ts
      working-directory: server

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install server dependencies
      run: npm install
      working-directory: server
      
    - name: Run ESLint - Server
      run: ./node_modules/.bin/eslint ./
      working-directory: server

    - name: Compile Typescript - Server
      run: ./node_modules/.bin/tsc
      working-directory: server

    - name: Codeball AI Code Review
      uses: sturdy-dev/codeball-action@v2.6.0


    - name: Build from Docker-Compose
      run: docker-compose -f docker-compose.yml -f development.yml build
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    - name: Launch containers
      run: docker-compose -f docker-compose.yml -f development.yml up -d
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    - name: Pull env vars from file
      run: source ./.env
      
    - name: Docker ps
      run: docker ps
            
    - name: Sleep for 5 seconds
      run: sleep 5s
      shell: bash
      
    - name: Docker logs
      run: docker-compose logs
    
    - name: Run tests
      run: WEEK=14 npm run test
      working-directory: server
